import torch 
from transformers import AutoModelForCausalLM, AutoTokenizer 
from PIL import Image 

class Vision:
    """
    Handles visual understanding using the Moondream2 model.
    """
    def __init__(self):
        print("[SYSTEM] Loading Vision model (Moondream)...")
        self.model_id = "vikhyatk/moondream2"
        self.revision = "2024-08-26"
        
        # Load the model with trust_remote_code=True as Moondream requires custom code execution
        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_id, 
            trust_remote_code=True, 
            revision=self.revision
        )
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_id, revision=self.revision)
        print("[SYSTEM] Vision model loaded.")

    def describe(self, image: Image.Image) -> str:
        """
        Generates a description for the provided image.
        
        Args:
            image (Image.Image): The input image.
            
        Returns:
            str: The description generated by the model.
        """
        enc_image = self.model.encode_image(image)
        description = self.model.answer_question(enc_image, "Describe this image.", self.tokenizer)
        return description